name: Deploy Weather App to Railway

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy Weather App to Railway
        run: railway up --service weather_mcp
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}

      - name: Railway Status
        run: railway status
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
